### PR TITLE
Add support for additional JDKs

### PR DESCRIPTION
**Pull request by joewiz**
Contains commits from https://bitbucket.org/infinitekind/appbundler/pull-requests/55. 

I will submit a follow-on PR removing this once that PR is merged.

### CODE REVIEW

**Comment by adamretter** [comment]
Hi Joe, thanks for this. You will need to also update the pom.xml please

**Comment by joewiz** [comment]
I'm not quite sure which portion of pom.xml needs to be updated - should I change https://github.com/evolvedbinary/appbundler-maven-build/blob/master/pom.xml#L15 to `1.1.0`, or something else?

**Comment by adamretter** [comment]
You need to add your patch to the patch plugin configuration, just search for `main.m` and you will see an example of an existing patch we apply. You will need something like:

```xml
<execution>
    <id>patch-native-dylibs</id>
    <phase>process-sources</phase>
    <goals>
        <goal>apply</goal>
    </goals>
    <configuration>
        <targetDirectory>${project.build.directory}/generated-sources/native</targetDirectory>
        <originalFile>${project.build.directory}/generated-sources/native/main.m</originalFile>
        <patches>
            <patch>find-dylibs.patch</patch>
        </patches>
    </configuration>
</execution>
```

Also your patch file actually contains 3 patches. It should contain just one which is the diff between main.m and HEAD of master branch, you may need to strip the paths in the patch file too, so that just the filename is present; take a look at one of the other patch files as an example

**Comment by joewiz** [comment]
Thanks for these hints! 

Getting the patch out of Mercurial was the hardest part for me (not being as familiar with Mercurial as I am with Git). I'm not sure why Sourcetree generates multi-commit patches that way. Luckily, I found [a way](https://stackoverflow.com/questions/1200691/with-mercurial-how-can-i-compress-a-series-of-changesets-into-one-before-push) to get [an all-in-one patch](https://bitbucket.org/!api/2.0/repositories/infinitekind/appbundler/diff/joewiz/appbundler:d60f62b02521%0D37899479fccf?from_pullrequest_id=55). 

With the revised PR, the build succeeds, and the relevant portion of the build completes with:

```
[INFO] --- maven-patch-plugin:1.2:apply (patch-native-logging) @ appbundler ---
[INFO] Applying patch: logging.patch
[INFO] 
[INFO] --- maven-patch-plugin:1.2:apply (patch-option-javadoc) @ appbundler ---
[INFO] Applying patch: option.patch
[INFO] 
[INFO] --- maven-patch-plugin:1.2:apply (patch-native-dylibs) @ appbundler ---
[INFO] Applying patch: find-dylibs.patch
```

I wish I knew how to directly test that *this* resulting build works as desired in eXist develop, but as I did the testing as noted in the upstream PR against a pre-mavened eXist develop, I'm confident it will work if this patch is applied as it appears to be. It seems like maven must have a way for me to build this, then use this local version of appbundler-maven instead of the one from maven central when building eXist. Clearly I have lots to learn about Maven.

**Comment by adamretter** [comment]
@joewiz If you wanted to test this then you would do something like this:

1. `mvn install` on this project. That will place a `1.1.0-SNAPSHOT` (as that is the version described in the `pom.xml`) of this project into your `~.m2/repository` folder.

2. Go to the `appbundler-maven-plugin` and modify its `pom.xml` to use the `<version>1.1.0-SNAPSHOT</version>` for this artifact, e.g.:

```xml
    <dependency>
      <groupId>com.evolvedbinary.appbundler</groupId>
      <artifactId>appbundler</artifactId>
      <version>1.0.1</version>
    </dependency>
```
3.

**Pull request merged**
